### ISSUE TITLE
Running TODO

### ISSUE THREAD

**Issue by morganhein** [2bit-software/gogo#1]
# TODO
- [ ] many tests. --version, --help, func listing, ?
- [ ] implement `gogo func FuncName --help`
- [ ] all config should be bubbled up into a .gogoconfig file
- [ ] finish implementing global cache
- [ ] add init subcommand to configure local and global global repos
- [x] auto-complete for function names in shell
- [ ] auto-complete function arguments in shell
- [x] remove the .SetLongDescription context function, and instead only use the function comment
- [ ] finish implementing affects of the gogo.Context details
- [ ] finish implementing single binary output
- [ ] finish implementing 1 binary per function build mode
- [ ] github actions workflows
- [ ] release process
- [ ] github pages/website to explain myself
- [ ] implement this https://magefile.org/compiling/ re: goos and goarch implementation
- [ ] implement something like this https://magefile.org/filesources/
- [ ] dep management: https://magefile.org/dependencies/ or https://github.com/DavidGamba/go-getoptions/blob/master/dag/README.adoc
- [ ] allow setting build tags when including the function library
- [ ] We should audit that none of the variables/inputs are reserved keywords
- [ ] or rename the inputs under the hood so they don't collide with reserved keywords
- [ ] audit the automatically generated sub-command environment variables. They are gross at the moment
- [x] Provide some option so that the generated main file is not deleted
- [x] Same with resulting binaries
- [x] Support functions that have error returns, handle the result, and do something with it
- [ ] implement the two ways to handle the gogo subcommand deps: either user managed, or we make a gogo_deps.go file that pins things, or we copy and stash their go.mod, get our deps, and then restore
